name: "Check for version update in PR to main"

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
    - main

jobs:
  main-pr-check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Check if version changed
      uses: ddbruce/action-main-pr-version-check@main